#! /bin/bash
set -e
if [ -n "$BUILDPACK_DEBUG" ]; then
  set -x
fi

function mktmpdir() {
  dir=$(mktemp -t graphicsmagick-$1-XXXX)
  rm -rf $dir
  mkdir -p $dir
  echo $dir
}

function archive_download() {
	local url="${1}"
	local location="${2}"

	mkdir -p "${location}"
	curl --location --silent "${url}" --output - \
		| tar --extract --xz --file - --directory="${location}" \
			--strip-components 1
}

source "$( dirname "${0}" )/../configs.sh"
source "$( dirname "${0}" )/lib/upload_buildpack_to_s3.sh"

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
  echo "must set AWS_ACCESS_KEY_ID"
  exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
  echo "must set AWS_SECRET_ACCESS_KEY"
  exit 1
fi

if [ -z "$AWS_SESSION_TOKEN" ]; then
  echo "must set AWS_SESSION_TOKEN"
  exit 1
fi

if [ -z "$STACK" ]; then
  echo "must set STACK to the scalingo stack being compiled for (i.e. STACK=scalingo-20)"
  exit 1
fi

pushd "$( dirname "${0}" )/.." >> /dev/null
home="$( pwd )"
popd >> /dev/null

VENDOR_GRAPHICS_MAGICK_ARCHIVE_URL="${VENDOR_GRAPHICS_MAGICK_ARCHIVE_URL:-"https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/${GRAPHICS_MAGICK_VERSION}/GraphicsMagick-${GRAPHICS_MAGICK_VERSION}.tar.xz/download"}"
basedir="$(cd -P "$(dirname "$0")" && pwd)"

echo ">>> Downloading GraphicsMagick"

# vendor directories
vendored_graphicsmagick_dir="$( mktmpdir graphicsmagick )"
archive_download "${VENDOR_GRAPHICS_MAGICK_ARCHIVE_URL}" "${vendored_graphicsmagick_dir}"

echo ">>> Building GraphicsMagick"

gm_local_path="/tmp/graphicsmagick-${GRAPHICS_MAGICK_VERSION}.tar.xz"
gm_lib_path="${BUILD_DIR}/vendor/graphicsmagick"
mkdir -p "${gm_lib_path}"

pushd "${vendored_graphicsmagick_dir}"
./configure
make
make DESTDIR="${gm_lib_path}" install
popd

echo ">>> Creating GraphicsMagick archive"
archive="GraphicsMagick-${GRAPHICS_MAGICK_VERSION}.tar.gz"

tar --create --gzip \
	--file "${archive}" \
	--directory="${vendored_graphicsmagick_dir}" \
	.

echo ">>> Uploading GraphicsMagick from ${archive} file"
s3_upload "${GRAPHICS_MAGICK_S3_BUCKET}" "${archive}" "${REMOTE_PATH}"
